export default {
    totalCount: 4393,
    dataList: [
        {
            id: 100014,
            channelCompanyId: 258,
            channelCompanyName:
                '数据同步消耗数据同步消耗数据同步消耗数据同步消耗数据同步消耗数据同步消耗数据同步消耗数据同步消耗数据同步消耗数据同步消耗数据同步消耗',
            principal: '数据同步消耗',
            principalWallet: null,
            channelTypeId: 1,
            channelTypeName: '应用商店',
            channelNameId: 366,
            channelName: '同步消耗数据1',
            channelAccount: null,
            channelAppId: 5,
            channelAppName: '榕树',
            createdTime: null,
            updateTime: 1573732194000,
            serialNumber: null,
            channelId: 'ucpz150',
            principalShow: '数据同步消耗'
        },
        {
            id: 100013,
            channelCompanyId: 258,
            channelCompanyName: '数据同步消耗',
            principal: '数据同步消耗',
            principalWallet: null,
            channelTypeId: 1,
            channelTypeName: '应用商店',
            channelNameId: 366,
            channelName: '同步消耗数据1同步消耗数据1同步消耗数据1同步消耗数据1同步消耗数据1',
            channelAccount: null,
            channelAppId: 5,
            channelAppName: '榕树',
            createdTime: null,
            updateTime: 1573732194000,
            serialNumber: null,
            channelId: 'bdydsempz21',
            principalShow: '数据同步消耗'
        },
        {
            id: 100008,
            channelCompanyId: 257,
            channelCompanyName: '同仁股份',
            principal: '张少',
            principalWallet: null,
            channelTypeId: 1,
            channelTypeName: '应用商店',
            channelNameId: 367,
            channelName: '同步消耗数据2',
            channelAccount: null,
            channelAppId: 5,
            channelAppName: '榕树',
            createdTime: null,
            updateTime: 1573725094000,
            serialNumber: null,
            channelId: 'ucpz104',
            principalShow: '张少'
        },
        {
            id: 100007,
            channelCompanyId: 258,
            channelCompanyName: '数据同步消耗',
            principal: '数据同步消耗',
            principalWallet: null,
            channelTypeId: 1,
            channelTypeName: '应用商店',
            channelNameId: 366,
            channelName: '同步消耗数据1',
            channelAccount: null,
            channelAppId: 5,
            channelAppName: '榕树',
            createdTime: null,
            updateTime: 1573732185000,
            serialNumber: null,
            channelId: 'ucpz74',
            principalShow: '数据同步消耗'
        },
        {
            id: 100006,
            channelCompanyId: 258,
            channelCompanyName: '数据同步消耗',
            principal: '数据同步消耗',
            principalWallet: null,
            channelTypeId: 1,
            channelTypeName: '应用商店',
            channelNameId: 365,
            channelName: '同步消耗数据',
            channelAccount: null,
            channelAppId: 5,
            channelAppName: '榕树',
            createdTime: null,
            updateTime: 1573725028000,
            serialNumber: null,
            channelId: 'ucpz60',
            principalShow: '数据同步消耗'
        },
        {
            id: 100004,
            channelCompanyId: 257,
            channelCompanyName: '同仁股份',
            principal: '张少',
            principalWallet: null,
            channelTypeId: 1,
            channelTypeName: '应用商店',
            channelNameId: 367,
            channelName: '同步消耗数据2',
            channelAccount: null,
            channelAppId: 5,
            channelAppName: '榕树',
            createdTime: null,
            updateTime: 1573725094000,
            serialNumber: null,
            channelId: 'smydsspz2',
            principalShow: '张少'
        },
        {
            id: 100003,
            channelCompanyId: 258,
            channelCompanyName: '数据同步消耗',
            principal: '数据同步消耗',
            principalWallet: null,
            channelTypeId: 1,
            channelTypeName: '应用商店',
            channelNameId: 366,
            channelName: '同步消耗数据1',
            channelAccount: null,
            channelAppId: 5,
            channelAppName: '榕树',
            createdTime: null,
            updateTime: 1573732182000,
            serialNumber: null,
            channelId: 'bdydsem1qx1',
            principalShow: '数据同步消耗'
        },
        {
            id: 100002,
            channelCompanyId: 258,
            channelCompanyName: '数据同步消耗',
            principal: '数据同步消耗',
            principalWallet: null,
            channelTypeId: 1,
            channelTypeName: '应用商店',
            channelNameId: 365,
            channelName: '同步消耗数据',
            channelAccount: null,
            channelAppId: 5,
            channelAppName: '榕树',
            createdTime: null,
            updateTime: 1573725081000,
            serialNumber: null,
            channelId: 'ucpz30',
            principalShow: '数据同步消耗'
        },
        {
            id: 100001,
            channelCompanyId: 9,
            channelCompanyName: '北京百传中云信息科技有限公司',
            principal: null,
            principalWallet: null,
            channelTypeId: 2,
            channelTypeName: '信息流',
            channelNameId: 101,
            channelName: '抖音（百传）',
            channelAccount: null,
            channelAppId: 5,
            channelAppName: '榕树',
            createdTime: null,
            updateTime: 1567403387000,
            serialNumber: null,
            channelId: 'wallet_huawei1',
            principalShow: null
        },
        {
            id: 10001,
            channelCompanyId: 242,
            channelCompanyName: 'oppo投放后台',
            principal: '测试人',
            principalWallet: null,
            channelTypeId: 18,
            channelTypeName: '应用商店（榕易有钱）',
            channelNameId: 291,
            channelName: 'oppo应用商店（榕易有钱）',
            channelAccount: null,
            channelAppId: 8,
            channelAppName: '榕易有钱',
            createdTime: 1567234651000,
            updateTime: 1567234751000,
            serialNumber: null,
            channelId: 'wallet_oppo1',
            principalShow: null
        }
    ]
};
